'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BasicPawn.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BasicPawnRedTop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BasicPawnRedTop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bmp_Stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bmp_Stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die stock any {FunctionName}(any val=0)
        '''{
        '''	if(FileExists(&quot;{IndentifierGUID}.ignore.bpdebug&quot;))
        '''	{
        '''		return val;
        '''	}
        '''	
        '''	Handle hTriggerFile = OpenFile(&quot;{IndentifierGUID}.trigger.bpdebug&quot;, &quot;w&quot;);
        '''	if(hTriggerFile == INVALID_HANDLE)
        '''		return val;
        '''
        '''	WriteFileLine(hTriggerFile, &quot;i:%d&quot;, val);
        '''	WriteFileLine(hTriggerFile, &quot;f:%f&quot;, val);
        '''	FlushFile(hTriggerFile);
        '''	CloseHandle(hTriggerFile);
        '''	
        '''	for(;;)
        '''	{
        '''		if(FileExists(&quot;{IndentifierGUID}.continue.bpdebug&quot;))
        '''		{
        '''			DeleteFile(&quot;{IndentifierGUID}.continue [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Debugger_BreakpointModuleNew() As String
            Get
                Return ResourceManager.GetString("Debugger_BreakpointModuleNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die stock any:{FunctionName}(any:val=0)
        '''{
        '''	if(FileExists(&quot;{IndentifierGUID}.ignore.bpdebug&quot;))
        '''	{
        '''		return val;
        '''	}
        '''	
        '''	new Handle:hTriggerFile = OpenFile(&quot;{IndentifierGUID}.trigger.bpdebug&quot;, &quot;w&quot;);
        '''	if(hTriggerFile == INVALID_HANDLE)
        '''		return val;
        '''
        '''	WriteFileLine(hTriggerFile, &quot;i:%d&quot;, val);
        '''	WriteFileLine(hTriggerFile, &quot;f:%f&quot;, val);
        '''	FlushFile(hTriggerFile);
        '''	CloseHandle(hTriggerFile);
        '''	
        '''	for(;;)
        '''	{
        '''		if(FileExists(&quot;{IndentifierGUID}.continue.bpdebug&quot;))
        '''		{
        '''			DeleteFile(&quot;{IndentifierGUID}.cont [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Debugger_BreakpointModuleOld() As String
            Get
                Return ResourceManager.GetString("Debugger_BreakpointModuleOld", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die #pragma semicolon 1
        '''
        '''#include &lt;sourcemod&gt;
        '''
        '''#define ENTITY_FULL_UPDATE_TIME 60.0
        '''#define MAXENTITIES 2048
        '''
        '''public Plugin:myinfo = 
        '''{
        '''	name = &quot;BasicPawn Debugger Module Runner&quot;,
        '''	author = &quot;Timocop&quot;,
        '''	description = &quot;BasicPawn debugger module which communicates with the debugger.&quot;,
        '''	version = &quot;1.0&quot;,
        '''	url = &quot;&quot;
        '''};
        '''
        '''enum EntityDebuggerAction 
        '''{
        '''	Action_Update,
        '''	Action_Remove,
        '''}
        '''
        '''public OnGameFrame()
        '''{
        '''	for(; /* Execute debugger commands */ ;)
        '''	{
        '''		if(!FileExists(&quot;{IndentifierGUID}.cmd.bpd [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Debugger_CommandRunnerEngineOld() As String
            Get
                Return ResourceManager.GetString("Debugger_CommandRunnerEngineOld", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die stock any {FunctionName}(any val=0)
        '''{
        '''	//if(FileExists(&quot;{IndentifierGUID}.value.bpdebug&quot;))
        '''	//	return val;
        '''
        '''	Handle hValFile = OpenFile(&quot;{IndentifierGUID}.value.bpdebug&quot;, &quot;w&quot;);
        '''	if(hValFile == INVALID_HANDLE)
        '''		return val;
        '''	
        '''	WriteFileLine(hValFile, &quot;i:%d&quot;, val);
        '''	WriteFileLine(hValFile, &quot;f:%f&quot;, val);
        '''	FlushFile(hValFile);
        '''	CloseHandle(hValFile);
        '''	
        '''	return val;
        '''} ähnelt.
        '''</summary>
        Friend ReadOnly Property Debugger_WatcherModuleNew() As String
            Get
                Return ResourceManager.GetString("Debugger_WatcherModuleNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die stock any:{FunctionName}(any:val=0)
        '''{
        '''	//if(FileExists(&quot;{IndentifierGUID}.value.bpdebug&quot;))
        '''	//	return val;
        '''
        '''	new Handle:hValFile = OpenFile(&quot;{IndentifierGUID}.value.bpdebug&quot;, &quot;w&quot;);
        '''	if(hValFile == INVALID_HANDLE)
        '''		return val;
        '''	
        '''	WriteFileLine(hValFile, &quot;i:%d&quot;, val);
        '''	WriteFileLine(hValFile, &quot;f:%f&quot;, val);
        '''	FlushFile(hValFile);
        '''	CloseHandle(hValFile);
        '''	
        '''	return val;
        '''} ähnelt.
        '''</summary>
        Friend ReadOnly Property Debugger_WatcherModuleOld() As String
            Get
                Return ResourceManager.GetString("Debugger_WatcherModuleOld", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5301_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5301_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5303_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5303_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5304_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5304_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5306_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5306_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5311_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5311_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5313_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5313_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5314_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5314_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5315_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5315_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5316_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5316_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5332_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5332_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5333_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5333_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5337_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5337_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5338_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5338_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5341_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5341_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5342_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5342_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5343_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5343_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5348_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5348_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5350_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5350_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5351_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5351_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5356_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5356_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5364_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5364_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5367_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5367_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5368_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5368_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageres_5372_16x16_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageres_5372_16x16-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;SyntaxDefinition name=&quot;SourcePawn-04e3632f-5472-42c5-929a-c3e0c2b35324&quot; extensions=&quot;.sp&quot;&gt;
        '''
        '''  &lt;Environment&gt; 
        '''    &lt;Default color=&quot;Black&quot; bgcolor=&quot;White&quot;/&gt;
        '''    &lt;Selection color=&quot;White&quot; bgcolor=&quot;RoyalBlue&quot;/&gt;
        '''    &lt;VRuler color=&quot;DarkGray&quot;/&gt;
        '''    &lt;InvalidLines color=&quot;Red&quot;/&gt;
        '''    &lt;CaretMarker color=&quot;LightCyan&quot;/&gt;
        '''    &lt;LineNumbers color=&quot;Gray&quot; bgcolor=&quot;White&quot;/&gt;
        '''    &lt;FoldLine color=&quot;LightGray&quot; bgcolor=&quot;White&quot;/&gt;
        '''    &lt;FoldMarker color=&quot;DarkGray&quot; bgcolor=&quot;White&quot;/&gt;
        '''    &lt;SelectedFoldLine co [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property SourcePawn_Syntax() As String
            Get
                Return ResourceManager.GetString("SourcePawn_Syntax", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
